### ISSUE TITLE
EpsilonConstraint doesn't terminate

### ISSUE THREAD

**Issue by odow** [jump-dev/MultiObjectiveAlgorithms.jl#50]
x-ref: https://discourse.julialang.org/t/multiobjectivealgorithms-epsilonconstraint-runs-infinitely/96178

```julia
using JuMP
import Ipopt
import MultiObjectiveAlgorithms as MOA

μ = [0.006898463772627643, -0.02972609131603086]
Q = [0.030446 0.00393731; 0.00393731  0.00713285]
Rf = 0
model = Model(() -> MOA.Optimizer(Ipopt.Optimizer))
set_silent(model)
set_optimizer_attribute(model, MOA.Algorithm(), MOA.EpsilonConstraint())
set_optimizer_attribute(model, MOA.SolutionLimit(), 25)
@variable(model, 0 <= w[1:2] <= 1)
@constraint(model, sum(w) == 1)
@expression(model, variance, w' * Q * w)
@expression(model, expected_return, w' * μ)
@variable(model, sharpe)
@NLconstraint(model, sharpe == (expected_return - Rf) / sqrt(variance)) 
@objective(model, Max, [expected_return, sharpe]) 
optimize!(model)
```

**Comment by kofgokhan** [comment]
The values for `left` and `right` within the ` EpsilonConstraint` are the same (they are not supposed to be). Thus, the method uses the same `epsilon` and keeps finding the same solution and we never reach the solution limit. I need to understand how `Hierarchical` works first.

Also, maybe we can change the name to `Sampling` as it was proposed before and add the implementation `EpsilonConstraint` by iteratively changing the epsilon based on the solution of the current iteration. We can augment the second objective with a small scalar initially to prevent a weakly efficient solution and update epsilon with `EpsilonConstraintStep`. The resulting implementation would generate the entire pareto set given sufficiently small `EpsilonConstraintStep`.

**Comment by kofgokhan** [comment]
> The values for left and right within the  EpsilonConstraint are the same (they are not supposed to be). 
On closer inspection, I think they are so close numerically that the epsilon in code is too small to make a significant shift.

**Comment by kofgokhan** [comment]
> Also, maybe we can change the name to Sampling as it was proposed before and add the implementation EpsilonConstraint by iteratively changing the epsilon based on the solution of the current iteration. We can augment the second objective with a small scalar initially to prevent a weakly efficient solution and update epsilon with EpsilonConstraintStep. The resulting implementation would generate the entire pareto set given sufficiently small EpsilonConstraintStep.

I see that this is already implemented in the case where `SolutionPoint` is at default.

Is the `weak_dom` only necessary when the user provides a `SolutionPoint`?

**Comment by odow** [comment]
We should add checks that to prevent the same solution being returned repeatedly. 

But this is really just a wrong algorithm for the model/poorly scaled model problem.

**Comment by xgandibleux** [comment]
> But this is really just a wrong algorithm for the model/poorly scaled model problem.

Indeed. 
The problem does not come from the algorithm implementation but from the usage done here.
