### ISSUE TITLE
KirlikSayin with unbounded objectives

### ISSUE THREAD

**Issue by odow** [jump-dev/MultiObjectiveAlgorithms.jl#60]
@xgandibleux says:

> I have prepared an exercise for my students which is a project planning 
> problem with 3 objectives, all the variables are discrete (ps: setting 
> the variables t_i >=0 is enough), see the attached document.
> 
> When I solve it with MOA.Lexicographic(all_permutations = true) I get a 
> result (ps: here I have to check the implementation because line 2 and 3 
> in the solution returned should be exchanged because we expect to get 
> the minimum on fct2 when fct2 is minimized, which is not the case - but 
> it is late now, maybe I don't see the obvious-).
> 
> When MOA.KirlikSayin() is called for solving this problem, a warning 
> appears and the resolution is stopped: "objective 1 does not have a 
> finite domain". If I am not wrong the initial conditions for applying KS 
> on this problem are fulfilled, right (objectives have bounded values). 
> Do you have any idea why this warning is raised and then the resolution 
> stopped?

Reproducible example
```Julia
julia> using JuMP

julia> import MultiObjectiveAlgorithms as MOA

julia> import HiGHS

julia> model = Model(() -> MOA.Optimizer(HiGHS.Optimizer))
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: MOA[algorithm=MultiObjectiveAlgorithms.Lexicographic, optimizer=HiGHS]

julia> set_silent(model)

julia> set_attribute(model, MOA.Algorithm(), MOA.KirlikSayin())

julia> @variable(model, x >= 0, Int)
x

julia> @variable(model, y >= 0, Int)
y

julia> @constraint(model, x + y >= 1)
x + y ≥ 1.0

julia> @objective(model, Min, 1.0 * [x, y])
2-element Vector{AffExpr}:
 x
 y

julia> optimize!(model)
┌ Warning: Unable to solve problem using `KirlikSayin()` because objective 1 does not have a finite domain.
└ @ MultiObjectiveAlgorithms ~/.julia/packages/MultiObjectiveAlgorithms/RdHL3/src/algorithms/KirlikSayin.jl:126
```

**Comment by remi-garcia** [comment]
It might be confusing since the nadir point is bounded if the problem is. However in KirlikSayin it is the worst point that is computed:

> y U is an over-estimator of the nadir point y N

after Equation (2).

____

In the current bi-objective case it seems that we should compute the nadir point as it is really simple from the lexicographic points. That makes this warning unexpected.

____

It might be a good idea to have dedicated functions to compute the nadir point and the worst case point.

**Comment by odow** [comment]
Does this new warning help? https://github.com/jump-dev/MultiObjectiveAlgorithms.jl/pull/64/files

We could provide a dedicated function for the nadir point in the biobjective case, but it seems like KirlikSaying etc are most useful for N > 2.

**Comment by remi-garcia** [comment]
The new warning is more explicit and will probably avoid some confusion 👍🏼 

I've just suggested changes to the warning to call it anti-ideal point instead of nadir point.
